### ISSUE TITLE
Support dir tag

### ISSUE THREAD

**Issue by bayaderpack** [jill64/svelte-i18n#151]
I need something for dir I cant find example. I have ar language and dir needs to be rtl. Is it possible to do something like this.

**Comment by jill64** [comment]
Thank you for opening this issue.

RTL is not currently supported, but we understand the need for it.
However, I do not have much knowledge about RTL and it will take some time to implement.

I am too busy to deal with this issue right now, but I will try to solve this problem in the near future.

**Comment by jill64** [comment]
RTL is presented by HTML markup.
For example, you can create your own Svelte components such as

```svelte
<script>
  import { translate, locale } from '$lib/i18n'
</script>

<p dir={$locale === 'ar' ? 'rtl' : 'ltr'}>
  {$translate({
    en: 'English',
    ar: 'عربي'
  })}
</p>
```

This is a bit exaggerated for a library to handle.
I would like to document such an example.
What do you think?

**Comment by bayaderpack** [comment]
Sorry I dont check for long time my email 😅
I do it with hooks.server.js just changing tag in html depends on the selected language.
